### PR TITLE
[WIP] Adding PnR test and 'small' config for faster testing

### PR DESCRIPTION
**Pull request by gatecat**
This requires https://gitlab.lip6.fr/vlsi-eda/coriolis/-/merge_requests/13 on the coriolis side.

Issues:
 - Grid alignment problems?
```
[WARNING] AnabaticEngine::computeEdgeCapacities(): <id:309130 RoutingPad core.soc_cpu_minerva_gprf_mem_mem_rdreg_0_d_16 [893.5um 1815um] <Occurrence <id:203683 Cell corona>:core.subckt_23120_sff1_x4:<id:3743 Vertical i li [4.5um 1.37um] [4.5um 8.63um] 0.17um>>> has no components on grid.
[WARNING] AnabaticEngine::computeEdgeCapacities(): <id:307679 RoutingPad core.abc_60564_new_n26708 [1123.535um 2174.93um] <Occurrence <id:203683 Cell corona>:core.subckt_19566_nor2_x0:<id:7114 Vertical nq li [1.535um 1.37um] [1.535um 8.49um] 0.17um>>> has no components on grid.
[WARNING] AnabaticEngine::computeEdgeCapacities(): <id:280304 RoutingPad core.soc_hyperram_signal_76 [2227.5um 1685um] <Occurrence <id:203683 Cell corona>:core.subckt_23304_sff1_x4:<id:3791 Vertical q li [13.5um 1.37um] [13.5um 8.63um] 0.17um>>> has no components on grid.
[WARNING] AnabaticEngine::computeEdgeCapacities(): <id:314264 RoutingPad core.abc_60564_new_n11856 [1987.5um 1664.5575um] <Occurrence <id:203683 Cell corona>:core.subckt_10431_mx2_x2:<id:1335 Vertical i0 li [1.5um 2.255um] [1.5um 8.63um] 0.17um>>> has no components on grid.
[WARNING] AnabaticEngine::computeEdgeCapacities(): <id:314263 RoutingPad core.abc_60564_new_n11856 [1861.5um 1665.1225um] <Occurrence <id:203683 Cell corona>:core.subckt_4718_a3_x2:<id:511 Vertical i2 li [2.5um 2.255um] [2.5um 7.5um] 0.17um>>> has no components on grid.
[WARNING] AnabaticEngine::computeEdgeCapacities(): <id:314262 RoutingPad core.abc_60564_new_n11856 [1911.5um 2395um] <Occurrence <id:203683 Cell corona>:core.subckt_4714_mx2_x2:<id:1111 Vertical q li [6.5um 1.37um] [6.5um 8.63um] 0.17um>>> has no components on grid.
[WARNING] AnabaticEngine::computeEdgeCapacities(): <id:320851 RoutingPad core.abc_60564_new_n25999 [1269.5um 2445um] <Occurrence <id:203683 Cell corona>:core.subckt_18858_o2_x2:<id:2138 Vertical i0 li [2.5um 1.37um] [2.5um 8.63um] 0.17um>>> has no components on grid.
[WARNING] AnabaticEngine::computeEdgeCapacities(): <id:320850 RoutingPad core.abc_60564_new_n25999 [1440.5um 2185um] <Occurrence <id:203683 Cell corona>:core.subckt_18857_oa22_x2:<id:2718 Vertical q li [4.5um 1.37um] [4.5um 8.63um] 0.17um>>> has no components on grid.
[WARNING] AnabaticEngine::computeEdgeCapacities(): <id:235389 RoutingPad core.abc_60564_new_n7214 [1797.5um 1125um] <Occurrence <id:203683 Cell corona>:core.subckt_182_nxr2_x1:<id:1963 Vertical i1 li [5.5um 1.37um] [5.5um 8.63um] 0.17um>>> has no components on grid.
[WARNING] AnabaticEngine::computeEdgeCapacities(): <id:235388 RoutingPad core.abc_60564_new_n7214 [1847.22um 1245um] <Occurrence <id:203683 Cell corona>:core.subckt_81_buf_x4:<id:6591 Vertical i li [0.78um 1.37um] [0.78um 8.63um] 0.17um>>> has no components on grid.
[WARNING] AnabaticEngine::computeEdgeCapacities(): <id:235387 RoutingPad core.abc_60564_new_n7214 [1772.5um 1115um] <Occurrence <id:203683 Cell corona>:core.subckt_73_o2_x2:<id:2138 Vertical i0 li [2.5um 1.37um] [2.5um 8.63um] 0.17um>>> has no components on grid.
[WARNING] AnabaticEngine::computeEdgeCapacities(): <id:235386 RoutingPad core.abc_60564_new_n7214 [1882.5um 2155um] <Occurrence <id:203683 Cell corona>:core.subckt_72_mx2_x2:<id:1111 Vertical q li [6.5um 1.37um] [6.5um 8.63um] 0.17um>>> has no components on grid.
```
and many more like it
 - Coriolis currently segfaults; possibly a problem with the above 'oeb' patch but I need to investigate
```
#0  Hurricane::Component::getNet() const (this=<optimized out>)
    at /home/gatecat/coriolis-2.x/Linux.x86_64/Release.Shared/install/include/coriolis2/hurricane/NetRoutingProperty.h:343
#1  Anabatic::AutoContact::getNet() const (this=<optimized out>)
    at /home/gatecat/coriolis-2.x/src/coriolis/anabatic/src/anabatic/AutoContact.h:233
#2  Anabatic::AutoSegment::create(Anabatic::AutoContact*, Anabatic::AutoContact*, Hurricane::Segment*) (source=source@entry=
    0x0, target=0x0, hurricaneSegment=hurricaneSegment@entry=0x55ac199b3e40)
    at /home/gatecat/coriolis-2.x/src/coriolis/anabatic/src/AutoSegment.cpp:2791
#3  0x00007fa94d69b536 in Anabatic::AnabaticEngine::setupPreRouteds() (this=this@entry=0x55ac2c4341a0)
    at /home/gatecat/coriolis-2.x/src/coriolis/anabatic/src/PreRouteds.cpp:216
#4  0x00007fa94d8c15e6 in Katana::KatanaEngine::digitalInit() (this=this@entry=0x55ac2c4341a0)
    at /home/gatecat/coriolis-2.x/src/coriolis/katana/src/KatanaEngine.cpp:254
#5  0x00007fa94d9192fd in Katana::PyKatanaEngine_digitalInit(Katana::PyKatanaEngine*) (self=0x7fa947ab2b50)
    at /home/gatecat/coriolis-2.x/src/coriolis/katana/src/PyKatanaEngine.cpp:168
```

### CODE REVIEW

**Comment by FatsieFS** [comment]
Maybe I should change something on the computation of the routing gauges or so. I compute them out of the design rules.
Checked my history and I don't see anything recently in these computations though.

**Comment by FatsieFS** [comment]
After further investigation it is seen that the li (e.g. first metal layer) is not marked anymore as CRL.RoutingLayerGauge.PinOnly but but as CRL.RoutingLayerGauge.Default. Need to check how that comes.

**Comment by FatsieFS** [comment]
Fixes should be available in #3 
Not fully tested as I have broken setup ATM.

**Comment by gatecat** [comment]
Merged; not yet DRC clean but basic PnR now working.

**Pull request merged**
